use full import for Nativescript 8
firescript/nativescript-contacts pull request #97
Opened 2021-05-27 20:38 UTC by tqhsonoma

Hi @firescript. Ryan, I made the changes so that the plug in will work for Nativescript 8. Please review and comment. Thanks. Thai

2021-06-04 05:01 UTC, Bidou44 commented
Actually it is working with nativescript 8, but you have to create alias in your webpack.config.

2021-06-21 12:43 UTC, firescript requested changes

2021-06-21 12:43 UTC, firescript commented on index.ios.js
> +const Frame = require("@nativescript/core//ui/frame").Frame;
@tqhsonoma double // - will this affect anything?

2021-07-13 17:52 UTC, tqhsonoma commented
Ryan, Typo fixed. Thai

2021-07-13 18:43 UTC, merged